// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAy-aPgORGiZUc_dpWldAyIA_OXd-Vf6k',
    appId: '1:333631013105:web:6a6f812ef8a8d009fa6950',
    messagingSenderId: '333631013105',
    projectId: 'absention-ae2c7',
    authDomain: 'absention-ae2c7.firebaseapp.com',
    storageBucket: 'absention-ae2c7.firebasestorage.app',
    measurementId: 'G-HP3Q2Z5NWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkrL2Q0_tZS-AysLEmhLu_AfY9DnqZNLk',
    appId: '1:333631013105:android:69bbb0c332e5c2f8fa6950',
    messagingSenderId: '333631013105',
    projectId: 'absention-ae2c7',
    storageBucket: 'absention-ae2c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6cSmKbGVCVuPHeHu7b_pHJ5tMU_WtSK8',
    appId: '1:333631013105:ios:448af01b5b71e894fa6950',
    messagingSenderId: '333631013105',
    projectId: 'absention-ae2c7',
    storageBucket: 'absention-ae2c7.firebasestorage.app',
    iosBundleId: 'com.example.absention',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6cSmKbGVCVuPHeHu7b_pHJ5tMU_WtSK8',
    appId: '1:333631013105:ios:448af01b5b71e894fa6950',
    messagingSenderId: '333631013105',
    projectId: 'absention-ae2c7',
    storageBucket: 'absention-ae2c7.firebasestorage.app',
    iosBundleId: 'com.example.absention',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAy-aPgORGiZUc_dpWldAyIA_OXd-Vf6k',
    appId: '1:333631013105:web:ec016825baca0561fa6950',
    messagingSenderId: '333631013105',
    projectId: 'absention-ae2c7',
    authDomain: 'absention-ae2c7.firebaseapp.com',
    storageBucket: 'absention-ae2c7.firebasestorage.app',
    measurementId: 'G-SRSSWWQJCL',
  );
}
